version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: st
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "db", "-U", "st" ]
      timeout: 45s
      interval: 10s
      retries: 10
  backend:
    build: ./todo
    privileged: true
    ports:
      - 8080:8080
    command:
      bash -c "
      python manage.py migrate &&
      python manage.py create_test_data admin 1 email@admin &&
      gunicorn todo.wsgi -b 0.0.0.0:8080"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx
