# Generated by Django 3.2.8 on 2021-10-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('birth_year', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
